# Generated by Django 3.2.7 on 2021-10-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemanager',
            name='active_members',
            field=models.IntegerField(default=0),
        ),
    ]
