# Generated by Django 3.2.7 on 2021-10-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0003_gamemanager_game_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemanager',
            name='Game_users',
            field=models.TextField(blank=True, null=True),
        ),
    ]
